version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: cems_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ../backend
    container_name: cems_backend
    env_file: ../.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build: ../frontend
    container_name: cems_frontend
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
